001 (2021267.006.000) 2023-02-06 10:44:37 Job executing on host: <131.169.77.166:45463?addrs=131.169.77.166-45463+[2001-638-700-104c--1-1a6]-45463&alias=bird646.desy.de>
...

Job started at Mon Feb 6 10:44:45 CET 2023 on bird646.desy.de

006 (2021267.006.000) 2023-02-06 10:44:46 Image size of job updated: 5124
	3  -  MemoryUsage of job (MB)
	2484  -  ResidentSetSize of job (KB)
...
EFTFitter is initialized with mode hybrid, event statistics counted as xsec...
Expecting as data a template with key data...

EFTFitter: iteration 0 starting...
EFTFitter: starting fit on variable b1k in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1k_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/4, with p-value 1
Best fit result c3, sample linear: 0 - 0.1158 + 0.1158 (1 sigma) - 0.2316 + 0.2316 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00033 + 1.00033 (1 sigma) - 4.00132 + 4.00132 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1k in iteration 0 saved for evolution scan...
EFTFitter: starting fit on variable b2k in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2k_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/4, with p-value 1
Best fit result c3, sample linear: 0 - 0.1169 + 0.1169 (1 sigma) - 0.2338 + 0.2338 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00004 + 1.00004 (1 sigma) - 4.00014 + 4.00014 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2k in iteration 0 saved for evolution scan...
EFTFitter: starting fit on variable b1r in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2r in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1n in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2n in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1j in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1j_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1j in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2j in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2j_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2j in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1q in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2q in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable ckk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_ckk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable ckk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable crr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_crr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable crr in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cnn in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cnn_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cnn in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cP_rk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cM_rk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cP_nr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nr in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cM_nr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nr in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cP_nk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cM_nk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cHel in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 0 doesn't result in a constraint!
EFTFitter: variable b1k with width 0.4632 is the best variable in iteration 0
EFTFitter: iteration 0 completed!
EFTFitter: iteration 1 starting...
Entering the IF 
  iVar0
EFTFitter: starting fit on variable b2k in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2k_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.07595 + 0.07595 (1 sigma) - 0.1519 + 0.1519 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00043 + 1.00043 (1 sigma) - 4.00173 + 4.00173 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2k in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b1r in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11205 + 0.11205 (1 sigma) - 0.22405 + 0.22405 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00045 + 1.00045 (1 sigma) - 4.00001 + 4.00001 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b2r in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11575 + 0.11575 (1 sigma) - 0.23145 + 0.23145 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00083 + 1.00083 (1 sigma) - 4.0016 + 4.0016 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b1n in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1135 + 0.1135 (1 sigma) - 0.22695 + 0.22695 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00047 + 1.00047 (1 sigma) - 4.00012 + 4.00012 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b2n in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1156 + 0.1156 (1 sigma) - 0.23115 + 0.23115 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00071 + 1.00071 (1 sigma) - 4.0011 + 4.0011 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 1 saved for evolution scan...
Entering the IF 
  iVar6
EFTFitter: starting fit on variable b2j in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2j_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11555 + 0.11555 (1 sigma) - 0.23105 + 0.23105 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00049 + 1.00049 (1 sigma) - 4.00024 + 4.00024 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2j in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b1q in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11395 + 0.11395 (1 sigma) - 0.22785 + 0.22785 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00065 + 1.00065 (1 sigma) - 4.00086 + 4.00086 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable b2q in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1158 + 0.1158 (1 sigma) - 0.23155 + 0.23155 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00056 + 1.00056 (1 sigma) - 4.00053 + 4.00053 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable ckk in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_ckk_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1126 + 0.1126 (1 sigma) - 0.22515 + 0.22515 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00085 + 1.00085 (1 sigma) - 4.00164 + 4.00164 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable ckk in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable crr in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_crr_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11525 + 0.11525 (1 sigma) - 0.23045 + 0.23045 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00047 + 1.00047 (1 sigma) - 4.00016 + 4.00016 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable crr in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cnn in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cnn_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11535 + 0.11535 (1 sigma) - 0.2307 + 0.2307 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00037 + 1.00037 (1 sigma) - 4.00147 + 4.00147 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cnn in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cP_rk in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11575 + 0.11575 (1 sigma) - 0.23145 + 0.23145 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00067 + 1.00067 (1 sigma) - 4.00096 + 4.00096 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1157 + 0.1157 (1 sigma) - 0.23135 + 0.23135 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00083 + 1.00083 (1 sigma) - 4.00159 + 4.00159 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cP_nr in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nr_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1148 + 0.1148 (1 sigma) - 0.22955 + 0.22955 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00048 + 1.00048 (1 sigma) - 4.00018 + 4.00018 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nr in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cM_nr in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nr_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1147 + 0.1147 (1 sigma) - 0.2294 + 0.2294 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00008 + 1.00008 (1 sigma) - 4.00031 + 4.00031 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nr in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cP_nk in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nk_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1155 + 0.1155 (1 sigma) - 0.23095 + 0.23095 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00074 + 1.00074 (1 sigma) - 4.00124 + 4.00124 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nk in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cM_nk in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nk_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.11515 + 0.11515 (1 sigma) - 0.2303 + 0.2303 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00012 + 1.00012 (1 sigma) - 4.00046 + 4.00046 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nk in iteration 1 saved for evolution scan...
EFTFitter: starting fit on variable cHel in iteration 1
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_1_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/9, with p-value 1
Best fit result c3, sample linear: 0 - 0.1152 + 0.1152 (1 sigma) - 0.23035 + 0.23035 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00059 + 1.00059 (1 sigma) - 4.00061 + 4.00061 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 1 saved for evolution scan...
EFTFitter: variable b2k with width 0.3038 is the best variable in iteration 1
EFTFitter: iteration 1 completed!
EFTFitter: iteration 2 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
EFTFitter: starting fit on variable b1r in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07525 + 0.07525 (1 sigma) - 0.15045 + 0.15045 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00073 + 1.00073 (1 sigma) - 4.00025 + 4.00025 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable b2r in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07515 + 0.07515 (1 sigma) - 0.15025 + 0.15025 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00106 + 1.00106 (1 sigma) - 4.00159 + 4.00159 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable b1n in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0751 + 0.0751 (1 sigma) - 0.15015 + 0.15015 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00086 + 1.00086 (1 sigma) - 4.00079 + 4.00079 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable b2n in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0753 + 0.0753 (1 sigma) - 0.1506 + 0.1506 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00061 + 1.00061 (1 sigma) - 4.00242 + 4.00242 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 2 saved for evolution scan...
Entering the IF 
  iVar6
Entering the IF 
  iVar7
EFTFitter: starting fit on variable b1q in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0755 + 0.0755 (1 sigma) - 0.151 + 0.151 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00019 + 1.00019 (1 sigma) - 4.00077 + 4.00077 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable b2q in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07535 + 0.07535 (1 sigma) - 0.1507 + 0.1507 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00053 + 1.00053 (1 sigma) - 4.00212 + 4.00212 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 2 saved for evolution scan...
Entering the IF 
  iVar10
EFTFitter: starting fit on variable crr in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_crr_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0752 + 0.0752 (1 sigma) - 0.1504 + 0.1504 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00003 + 1.00003 (1 sigma) - 4.00012 + 4.00012 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable crr in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cnn in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cnn_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07455 + 0.07455 (1 sigma) - 0.1491 + 0.1491 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00014 + 1.00014 (1 sigma) - 4.00056 + 4.00056 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cnn in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cP_rk in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07565 + 0.07565 (1 sigma) - 0.1513 + 0.1513 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00004 + 1.00004 (1 sigma) - 4.00014 + 4.00014 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0758 + 0.0758 (1 sigma) - 0.15155 + 0.15155 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00119 + 1.00119 (1 sigma) - 4.0021 + 4.0021 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cP_nr in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nr_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0738 + 0.0738 (1 sigma) - 0.1476 + 0.1476 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00054 + 1.00054 (1 sigma) - 4.00216 + 4.00216 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nr in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cM_nr in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nr_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07395 + 0.07395 (1 sigma) - 0.14785 + 0.14785 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00131 + 1.00131 (1 sigma) - 4.00254 + 4.00254 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nr in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cP_nk in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nk_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0756 + 0.0756 (1 sigma) - 0.15115 + 0.15115 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.001 + 1.001 (1 sigma) - 4.00136 + 4.00136 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nk in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cM_nk in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nk_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.0751 + 0.0751 (1 sigma) - 0.15015 + 0.15015 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00068 + 1.00068 (1 sigma) - 4.00005 + 4.00005 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nk in iteration 2 saved for evolution scan...
EFTFitter: starting fit on variable cHel in iteration 2
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_2_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/14, with p-value 1
Best fit result c3, sample linear: 0 - 0.07525 + 0.07525 (1 sigma) - 0.1505 + 0.1505 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00038 + 1.00038 (1 sigma) - 4.00151 + 4.00151 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 2 saved for evolution scan...
EFTFitter: variable cP_nr with width 0.2952 is the best variable in iteration 2
EFTFitter: iteration 2 completed!
EFTFitter: iteration 3 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
EFTFitter: starting fit on variable b1r in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07335 + 0.07335 (1 sigma) - 0.14665 + 0.14665 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00086 + 1.00086 (1 sigma) - 4.0007 + 4.0007 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable b2r in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07335 + 0.07335 (1 sigma) - 0.14665 + 0.14665 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00083 + 1.00083 (1 sigma) - 4.00058 + 4.00058 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable b1n in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.0727 + 0.0727 (1 sigma) - 0.1454 + 0.1454 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00027 + 1.00027 (1 sigma) - 4.00109 + 4.00109 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable b2n in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.0729 + 0.0729 (1 sigma) - 0.14575 + 0.14575 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00101 + 1.00101 (1 sigma) - 4.00131 + 4.00131 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 3 saved for evolution scan...
Entering the IF 
  iVar6
Entering the IF 
  iVar7
EFTFitter: starting fit on variable b1q in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07355 + 0.07355 (1 sigma) - 0.1471 + 0.1471 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00009 + 1.00009 (1 sigma) - 4.00036 + 4.00036 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable b2q in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.0735 + 0.0735 (1 sigma) - 0.14695 + 0.14695 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00099 + 1.00099 (1 sigma) - 4.00123 + 4.00123 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 3 saved for evolution scan...
Entering the IF 
  iVar10
EFTFitter: starting fit on variable crr in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_crr_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07305 + 0.07305 (1 sigma) - 0.14605 + 0.14605 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00131 + 1.00131 (1 sigma) - 4.00251 + 4.00251 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable crr in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable cnn in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cnn_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07085 + 0.07085 (1 sigma) - 0.1417 + 0.1417 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00008 + 1.00008 (1 sigma) - 4.00032 + 4.00032 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cnn in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable cP_rk in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07345 + 0.07345 (1 sigma) - 0.1469 + 0.1469 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00046 + 1.00046 (1 sigma) - 4.00186 + 4.00186 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.0735 + 0.0735 (1 sigma) - 0.147 + 0.147 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00045 + 1.00045 (1 sigma) - 4.0018 + 4.0018 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 3 saved for evolution scan...
Entering the IF 
  iVar15
Entering the IF 
  iVar16
EFTFitter: starting fit on variable cP_nk in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nk_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.0735 + 0.0735 (1 sigma) - 0.147 + 0.147 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00018 + 1.00018 (1 sigma) - 4.00072 + 4.00072 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nk in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable cM_nk in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nk_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07325 + 0.07325 (1 sigma) - 0.14645 + 0.14645 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00104 + 1.00104 (1 sigma) - 4.00141 + 4.00141 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_nk in iteration 3 saved for evolution scan...
EFTFitter: starting fit on variable cHel in iteration 3
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_3_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/19, with p-value 1
Best fit result c3, sample linear: 0 - 0.07315 + 0.07315 (1 sigma) - 0.14625 + 0.14625 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00123 + 1.00123 (1 sigma) - 4.00219 + 4.00219 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 3 saved for evolution scan...
EFTFitter: variable cnn with width 0.2834 is the best variable in iteration 3
EFTFitter: iteration 3 completed!
EFTFitter: iteration 4 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
EFTFitter: starting fit on variable b1r in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.0677 + 0.0677 (1 sigma) - 0.13535 + 0.13535 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00142 + 1.00142 (1 sigma) - 4.00273 + 4.00273 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 4 saved for evolution scan...
EFTFitter: starting fit on variable b2r in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.06745 + 0.06745 (1 sigma) - 0.1349 + 0.1349 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00062 + 1.00062 (1 sigma) - 4.00248 + 4.00248 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 4 saved for evolution scan...
EFTFitter: starting fit on variable b1n in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.07085 + 0.07085 (1 sigma) - 0.14165 + 0.14165 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00129 + 1.00129 (1 sigma) - 4.00233 + 4.00233 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 4 saved for evolution scan...
EFTFitter: starting fit on variable b2n in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.07085 + 0.07085 (1 sigma) - 0.14165 + 0.14165 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00091 + 1.00091 (1 sigma) - 4.00082 + 4.00082 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 4 saved for evolution scan...
Entering the IF 
  iVar6
Entering the IF 
  iVar7
EFTFitter: starting fit on variable b1q in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.0682 + 0.0682 (1 sigma) - 0.1364 + 0.1364 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.0001 + 1.0001 (1 sigma) - 4.00039 + 4.00039 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 4 saved for evolution scan...
EFTFitter: starting fit on variable b2q in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.0679 + 0.0679 (1 sigma) - 0.1358 + 0.1358 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00058 + 1.00058 (1 sigma) - 4.00233 + 4.00233 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 4 saved for evolution scan...
Entering the IF 
  iVar10
Entering the IF 
  iVar11
Entering the IF 
  iVar12
EFTFitter: starting fit on variable cP_rk in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.07075 + 0.07075 (1 sigma) - 0.14145 + 0.14145 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.0013 + 1.0013 (1 sigma) - 4.00239 + 4.00239 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 4 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.0708 + 0.0708 (1 sigma) - 0.1416 + 0.1416 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00053 + 1.00053 (1 sigma) - 4.00212 + 4.00212 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 4 saved for evolution scan...
Entering the IF 
  iVar15
Entering the IF 
  iVar16
Entering the IF 
  iVar17
Entering the IF 
  iVar18
EFTFitter: starting fit on variable cHel in iteration 4
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_4_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/24, with p-value 1
Best fit result c3, sample linear: 0 - 0.06975 + 0.06975 (1 sigma) - 0.1395 + 0.1395 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00013 + 1.00013 (1 sigma) - 4.0005 + 4.0005 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 4 saved for evolution scan...
EFTFitter: variable b2r with width 0.2698 is the best variable in iteration 4
EFTFitter: iteration 4 completed!
EFTFitter: iteration 5 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
Entering the IF 
  iVar2
Entering the IF 
  iVar3
EFTFitter: starting fit on variable b1n in iteration 5
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_5_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/29, with p-value 1
Best fit result c3, sample linear: 0 - 0.0661 + 0.0661 (1 sigma) - 0.13215 + 0.13215 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00099 + 1.00099 (1 sigma) - 4.00095 + 4.00095 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 5 saved for evolution scan...
Entering the IF 
  iVar5
Entering the IF 
  iVar6
Entering the IF 
  iVar7
Entering the IF 
  iVar8
Entering the IF 
  iVar9
Entering the IF 
  iVar10
Entering the IF 
  iVar11
Entering the IF 
  iVar12
EFTFitter: starting fit on variable cP_rk in iteration 5
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_5_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/29, with p-value 1
Best fit result c3, sample linear: 0 - 0.06735 + 0.06735 (1 sigma) - 0.1347 + 0.1347 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00043 + 1.00043 (1 sigma) - 4.00171 + 4.00171 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 5 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 5
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_5_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/29, with p-value 1
Best fit result c3, sample linear: 0 - 0.0674 + 0.0674 (1 sigma) - 0.1348 + 0.1348 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00066 + 1.00066 (1 sigma) - 4.00265 + 4.00265 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 5 saved for evolution scan...
Entering the IF 
  iVar15
Entering the IF 
  iVar16
Entering the IF 
  iVar17
Entering the IF 
  iVar18
EFTFitter: starting fit on variable cHel in iteration 5
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cHel_iter_5_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/29, with p-value 1
Best fit result c3, sample linear: 0 - 0.066 + 0.066 (1 sigma) - 0.13195 + 0.13195 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00125 + 1.00125 (1 sigma) - 4.00197 + 4.00197 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cHel in iteration 5 saved for evolution scan...
EFTFitter: variable cHel with width 0.2639 is the best variable in iteration 5
EFTFitter: iteration 5 completed!
EFTFitter: iteration 6 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
Entering the IF 
  iVar2
Entering the IF 
  iVar3
EFTFitter: starting fit on variable b1n in iteration 6
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_6_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/34, with p-value 1
Best fit result c3, sample linear: 0 - 0.0638 + 0.0638 (1 sigma) - 0.1276 + 0.1276 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00056 + 1.00056 (1 sigma) - 4.00223 + 4.00223 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 6 saved for evolution scan...
Entering the IF 
  iVar5
Entering the IF 
  iVar6
Entering the IF 
  iVar7
Entering the IF 
  iVar8
Entering the IF 
  iVar9
Entering the IF 
  iVar10
Entering the IF 
  iVar11
Entering the IF 
  iVar12
EFTFitter: starting fit on variable cP_rk in iteration 6
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_6_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/34, with p-value 1
Best fit result c3, sample linear: 0 - 0.0659 + 0.0659 (1 sigma) - 0.1318 + 0.1318 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00002 + 1.00002 (1 sigma) - 4.00009 + 4.00009 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 6 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 6
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_6_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/34, with p-value 1
Best fit result c3, sample linear: 0 - 0.0657 + 0.0657 (1 sigma) - 0.13135 + 0.13135 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00103 + 1.00103 (1 sigma) - 4.00105 + 4.00105 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 6 saved for evolution scan...
Entering the IF 
  iVar15
Entering the IF 
  iVar16
Entering the IF 
  iVar17
Entering the IF 
  iVar18
Entering the IF 
  iVar19
EFTFitter: variable b1n with width 0.2552 is the best variable in iteration 6
EFTFitter: iteration 6 completed!
EFTFitter: iteration 7 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
Entering the IF 
  iVar2
Entering the IF 
  iVar3
Entering the IF 
  iVar4
Entering the IF 
  iVar5
Entering the IF 
  iVar6
Entering the IF 
  iVar7
Entering the IF 
  iVar8
Entering the IF 
  iVar9
Entering the IF 
  iVar10
Entering the IF 
  iVar11
Entering the IF 
  iVar12
EFTFitter: starting fit on variable cP_rk in iteration 7
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_7_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/39, with p-value 1
Best fit result c3, sample linear: 0 - 0.06335 + 0.06335 (1 sigma) - 0.1267 + 0.1267 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00028 + 1.00028 (1 sigma) - 4.00112 + 4.00112 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 7 saved for evolution scan...
EFTFitter: starting fit on variable cM_rk in iteration 7
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as finalcov

Drawing the requested covariance matrices...
finalcov

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_7_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at 0 with chi2/nDoF 0/39, with p-value 1
Best fit result c3, sample linear: 0 - 0.06115 + 0.06115 (1 sigma) - 0.12225 + 0.12225 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 1.00151 + 1.00151 (1 sigma) - 4.00275 + 4.00275 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 7 saved for evolution scan...
Entering the IF 
  iVar15
Entering the IF 
  iVar16
Entering the IF 
  iVar17
Entering the IF 
  iVar18
Entering the IF 
  iVar19
EFTFitter: variable cM_rk with width 0.2445 is the best variable in iteration 7
EFTFitter: iteration 7 completed!
EFTFitter: iteration 8 starting...
Entering the IF 
  iVar0
Entering the IF 
  iVar1
Entering the IF 
  iVar2
Entering the IF 
  iVar3
Entering the IF 
  iVar4
Entering the IF 
  iVar5
Entering the IF 
  iVar6
Entering the IF 
  iVar7
Entering the IF 
  iVar8
Entering the IF 
  iVar9
Entering the IF 
  iVar10
Entering the IF 
  iVar11
Entering the IF 
  iVar12
Entering the IF 
  iVar13
Entering the IF 
  iVar14
Entering the IF 
  iVar15
Entering the IF 
  iVar16
Entering the IF 
  iVar17
Entering the IF 
  iVar18
Entering the IF 
  iVar19
EFTFitter: iteration 8 aborted; no further variables can make up an independent set.

Job stoped at Mon Feb 6 10:54:29 CET 2023 on bird646.desy.de

005 (2021267.006.000) 2023-02-06 10:54:29 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:05:53, Sys 0 00:00:05  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:05:53, Sys 0 00:00:05  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :     0.71        1         1 
	   Disk (KB)            :     1    20480000  21449495 
	   Memory (MB)          :   130        1536      1536 

	Job terminated of its own accord at 2023-02-06T09:54:29Z.
...
