001 (2021266.006.000) 2023-02-06 10:42:59 Job executing on host: <131.169.77.175:40445?addrs=131.169.77.175-40445+[2001-638-700-104c--1-1af]-40445&alias=bird655.desy.de>
...

Job started at Mon Feb 6 10:43:05 CET 2023 on bird655.desy.de

EFTFitter is initialized with mode hybrid, event statistics counted as xsec...
Expecting as data a template with key data...

006 (2021266.006.000) 2023-02-06 10:43:08 Image size of job updated: 94212
	9  -  MemoryUsage of job (MB)
	8400  -  ResidentSetSize of job (KB)
...
EFTFitter: iteration 0 starting...
EFTFitter: starting fit on variable b1k in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1k_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1k in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2k in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2k_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2k in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1r in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1r_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1r in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2r in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2r_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2r in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1n in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1n_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1n in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2n in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2n_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2n in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1j in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1j_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1j in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2j in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2j_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2j in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b1q in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b1q_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b1q in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable b2q in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_b2q_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable b2q in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable ckk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_ckk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable ckk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable crr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_crr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable crr in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cnn in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cnn_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cnn in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cP_rk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_rk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_rk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cM_rk in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_rk_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cM_rk in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cP_nr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cP_nr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

Drawing the 1D dChi2 graph for each operator...

Minimum for op c3, sample linear found at -0.5 with chi2/nDoF 0/4, with p-value 1
Requested fit range for operator c3 is insufficient to define the 1 sigma bands! Skipping...
Requested fit range for operator c3 is insufficient to define the 2 sigma bands! Skipping...
Best fit result c3, sample linear: -0.5 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Best fit dChi2 c3, sample linear: 0 - 0 + 0 (1 sigma) - 0 + 0 (2 sigma)
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_dChi2.pdf has been created

Clearing up contents of the current EFTFitter object...

Chi2 values and corresponding keys cleared.

All EFTFitter object content cleared.

EFTFitter: fit on variable cP_nr in iteration 0 doesn't result in a constraint!
EFTFitter: starting fit on variable cM_nr in iteration 0
Adding input with key c3_0 of type all...

Adding input with key c3_1 of type all...

Adding input with key c3_-1 of type all...

Preparing the base contents for all operators...
Contribution of each operator at 1 (in xsec) is:
[ [ c3 :: linear ] :: 0.2265, 0 ]
[ [ c3 :: quadratic ] :: -1.95156e-17, 0 ]
For reference: SM xsec is 0.598143, 0

Assigning key c3_0 of type linear as data...
Note: previous data is overwritten by this method!!

Reading matrix TotalStatCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatStat_purdue_full2016.root and assigning it as totalStat

Reading matrix TotalSystCovMatrix_AllVarNorm_rebinnedA from file /nfs/dust/cms/user/zimermma/EFTFitter/inputs/covariance_matrix/covMatSyst_purdue_full2016.root and assigning it as totalSyst

Drawing the requested covariance matrices...
finalcov
totalStat
totalSyst

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_finalcov.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalStat.pdf has been created
Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/cov_totalSyst.pdf has been created

Drawing the requested key-sample templates ...
[ c3_-1 :: all ]
[ c3_1 :: all ]
[ c3_0 :: all ]
[ data :: all ]

Info in <TCanvas::Print>: pdf file /nfs/dust/cms/user/zimermma/EFTFitter/fit_output/ttbareft_translationp_Breuther_dim6top_reweighting_13TeV/TotalSystStatCovMatrix_AllVarNorm_rebinnedA/c3/c3_var_cM_nr_iter_0_shape.pdf has been created

Unpacking the grid of requested operator values into individual keys...

Computing the chi2 for all requested keys...

006 (2021266.006.000) 2023-02-06 10:44:17 Image size of job updated: 599800
	122  -  MemoryUsage of job (MB)
	124016  -  ResidentSetSize of job (KB)
...
004 (2021266.006.000) 2023-02-06 10:44:17 Job was evicted.
	(0) CPU times
		Usr 0 00:00:36, Sys 0 00:00:01  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :                 1         1 
	   Disk (KB)            :        1 20480000  21252672 
	   Memory (MB)          :      122     1536      1536 
...
009 (2021266.006.000) 2023-02-06 10:44:17 Job was aborted.
	via condor_rm (by user zimermma)
...
